### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Added a banner and few other minor changes.
I used the provided banner, I think it's a little too big however. So if I am allowed I can make a banner that fits better. 😊

### Adresses: #2 

image

### CODE REVIEW

**Comment by ikurotime** [comment]
@nebocoder That looks great! Yes, you are allowed to make suggestions, let's se it!

**Comment by ghost** [comment]
> @nebocoder That looks great! Yes, you are allowed to make suggestions, let's se it!

Do you have a logo svg, or should it just be any icon with the same style?

**Comment by ikurotime** [comment]
> > @nebocoder That looks great! Yes, you are allowed to make suggestions, let's se it!
> 
> Do you have a logo svg, or should it just be any icon with the same style?

The images are from this website: https://icons8.com/icon/set/weather/stickers
You can find the ones used in the project here: https://github.com/ikurotime/GeoWeather/tree/master/src/img
I think you can grab only the .png ones.

**Comment by ghost** [comment]
I will make a new PR with the updated readme.

**Pull request closed without merging**
